### ISSUE TITLE
Where to find the Simple-Align

### ISSUE THREAD

**Issue by br-pp** [Dreamzz5/Simple-Align#1]
Thank you for your job! Could you please indicate where the method Simple-Align is implemented in the code?

**Comment by CuddleSabe** [comment]
that's a shame work
he use "repeat(2, 1, 1, 1)" to make one image has two degradation in a batch.
but I found he use the "_dequeue_and_enqueue", it will shuffle the batch and break the "one image has two degradation in a batch"
what the ****

**Comment by Dreamzz5** [comment]
please refer to https://github.com/Dreamzz5/Simple-Align/blob/3e0b39f186aa117d7cd8f9f86ec430965321cd17/realesrgan/models/realesrnet_model.py#L217.

**Comment by br-pp** [comment]
thank you!

**Comment by Chenweihai666** [comment]
Thank you for your work! I want to know if it's possible to simply replace Dropout with lines 217-233 of code and use it?

**Comment by Dreamzz5** [comment]
Dropout can be done by referring to RDSR https://github.com/XPixelGroup/RDSR/tree/main.
