### ISSUE TITLE
<BUG> wrong implement

### ISSUE THREAD

**Issue by CuddleSabe** [Dreamzz5/Simple-Align#2]
hi, I found u use "repeat(2, 1, 1, 1)" to make one image has two degradation in a batch.
but I found u use the "_dequeue_and_enqueue", it will shuffle the batch and break the "one image has two degradation in a batch"
what the ****

**Comment by Dreamzz5** [comment]
Thank you for your report. We have mistakenly uploaded the test version of code here. In our test setting we make each dataloader have two identical ground truths, so there is no need for an expand operation, which ensures that the queue_size on each GPU card is equal to 8 < queue_size (16). As you mentioned, if self.queue_ptr != self.queue_size, shuffle operation won't be executed. We have uploaded the latest version of our code with line "_dequeue_and_enqueue" commented out. Feel feel to reproduce our results.
