### ISSUE TITLE
Code for adding degradation missing

### ISSUE THREAD

**Issue by Andrew-Ma-2001** [Dreamzz5/Simple-Align#5]
In the readme file 
~~~bash
cd ./dataset
python add_degradations.py
~~~
while not finding any dir named dataset, and nor file add_degradations.py

**Comment by Dreamzz5** [comment]
Please put the dataset into the dataset folder according to the first step.

**Comment by Andrew-Ma-2001** [comment]
I mean, i can't find the add_degradations.py file; the code wasn't appearing in this github repo.

I have downlowed all the given test files, but cannot find it. Any chance you could check the repo and point out where this file or code for adding degradations?

**Comment by Dreamzz5** [comment]
Sorry, this part has not been provided. You can refer to RDSR at https://github.com/XPixelGroup/RDSR/tree/main/dataset.

**Comment by Andrew-Ma-2001** [comment]
I fully understand the concern for not providing the code, for fair comparison on your methods, can you share the noise parameter settings for generating the noise dataset in the paper?

**Comment by Dreamzz5** [comment]
Sorry for the confusion. We are using the same degradation parameters as RDSR. You can directly use the code from https://github.com/XPixelGroup/RDSR/blob/main/dataset/add_degradations.py.
